# Generated by Django 2.1.3 on 2018-11-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181121_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apistep',
            name='Apitest',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='Product',
        ),
        migrations.DeleteModel(
            name='Apistep',
        ),
        migrations.DeleteModel(
            name='Apitest',
        ),
    ]
