# Generated by Django 2.1.3 on 2018-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productdesc',
            field=models.CharField(max_length=200, verbose_name='产品描述'),
        ),
    ]
