# Generated by Django 2.1.3 on 2018-11-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcase',
            options={'verbose_name': 'app测试用例', 'verbose_name_plural': 'app测试用例'},
        ),
    ]
